database:
  host: "localhost"
  port: "5444"
  user: "postgres"
  password: "12345"
  dbname: "postgres"

http_server:
  address: ":8080"
  timeout: 4s
  idle_timeout: 59s

kafka:
  brokers:
    - "localhost:9092"
  topic: "user-segments"