// Code generated by mockery v2.49.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IUserSegmentHistoryService is an autogenerated mock type for the IUserSegmentHistoryService type
type IUserSegmentHistoryService struct {
	mock.Mock
}

// GenerateUserHistoryCSV provides a mock function with given fields: userID, date
func (_m *IUserSegmentHistoryService) GenerateUserHistoryCSV(userID int64, date string) (string, error) {
	ret := _m.Called(userID, date)

	if len(ret) == 0 {
		panic("no return value specified for GenerateUserHistoryCSV")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, string) (string, error)); ok {
		return rf(userID, date)
	}
	if rf, ok := ret.Get(0).(func(int64, string) string); ok {
		r0 = rf(userID, date)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = rf(userID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIUserSegmentHistoryService creates a new instance of IUserSegmentHistoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserSegmentHistoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserSegmentHistoryService {
	mock := &IUserSegmentHistoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
